//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pingladevi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Pavati
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string Mobileno { get; set; }
        public string PaymentInWord { get; set; }
        public string PaymentInNo { get; set; }
    }
}
